site_name: Projeto Banco de Dados - Munchkin

theme:
  name: material
  features:
    - navigation.instant         # navegação sem recarregar
    - navigation.tracking        # marca onde você está no menu
    - navigation.tabs            # adiciona abas no topo
    - navigation.tabs.sticky     # as abas ficam fixas
    - navigation.top             # botão para voltar ao topo

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber    # fundo claro amarelado, puxando para o ouro
      accent: red       # detalhes em vermelho, como no título do jogo
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber    # mantém dourado no modo escuro também
      accent: red
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro

  language: pt-BR

nav:
  - Início: "index.md"
  - Módulo 1:
      - Modelo ER: "modulo01/mer.md"
      - Diagrama ER: "modulo01/der.md"
  - Módulo 2:
      - DDL: "modulo02/DDL.md"
